# Generated by Django 2.2.6 on 2019-11-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191124_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
